name: Stonington Financial Group
favicon: null
layout_spectrum: 0.51450489833951
typography_spectrum: 0.514640451176092
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.0355234663002193
  lightness: 0.2454233099706471
  saturation: 0.6127575165592134
  rhythmicContrast: 0.7978737417142838
purpose: []
