name: Stonington Financial Group
favicon: null
layout_spectrum: 0.2479
typography_spectrum: 0.49328
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#003f67'
    - '#ffffff'
    - '#c5c5c5'
    - '#628cae'
  brandStrength: 0.25
  lightness: 0.875
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
