name: Stonington Financial Group
favicon: null
layout_spectrum: 0.51450489833951
typography_spectrum: 0.74601
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#231f20'
    - '#003f67'
    - '#ffffff'
    - '#c5c5c5'
    - '#628cae'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.6127575165592134
  rhythmicContrast: 0.7978737417142838
purpose: []
